version = 5.7.0
archive_dir = /etc/letsencrypt/archive/steelflowmrp.com
cert = /etc/letsencrypt/live/steelflowmrp.com/cert.pem
privkey = /etc/letsencrypt/live/steelflowmrp.com/privkey.pem
chain = /etc/letsencrypt/live/steelflowmrp.com/chain.pem
fullchain = /etc/letsencrypt/live/steelflowmrp.com/fullchain.pem
[renewalparams]
account = eec5b82e7e870a3fff854e400da0fe51
authenticator = webroot
webroot_path = /var/www/public,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
steelflowmrp.com = /var/www/public
